[package]
name = "aoc2020"
version = "0.1.0"
authors = ["iliana etaoin <iliana@buttslol.net>"]
edition = "2018"
publish = false

[dependencies]
heapless = "0.5"
itertools = { version = "0.9", default-features = false }
libc-print = "0.1"

[dev-dependencies]
assert_cmd = "1"
paste = "1"
